version: "3"

services:
  proxy: 
    image: jwilder/nginx-proxy 
    volumes: 
    - /var/run/docker.sock:/tmp/docker.sock:ro 
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
     - 80:80
  front:
    build: ./front/
    ports:
      - 5000:5000
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=salainen
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  back:
    build: ./back/
    environment: 
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=salainen
    ports:
      - 8000:8000
  

   